config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :models
  resources :dealers
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Brand < ApplicationRecord
  has_many :models
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :bigint           not null, primary key
#  name       :string
#  fueltype   :string
#  bodytype   :string
#  gearbox    :string
#  price      :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Car < ApplicationRecord
end

app/models/dealer.rb
# == Schema Information
#
# Table name: dealers
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Dealer < ApplicationRecord
end

app/models/model.rb
# == Schema Information
#
# Table name: models
#
#  id          :bigint           not null, primary key
#  brand_id    :integer
#  parent_id   :integer
#  name        :string
#  cars_count  :integer
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Model < ApplicationRecord
  belongs_to :parent,
    class_name: 'Model',
    optional: true,
    inverse_of: :sub_models

  has_many :sub_models,
    class_name: 'Model',
    foreign_key: 'parent_id',
    inverse_of: :parent

  belongs_to :brand

  def brand_with_model
    "#{brand.name} #{name}"
  end

  scope :prime_models, -> {where("models.parent_id is null")}
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
    @models = Model.prime_models
    @brands = Brand.all
  end

  # GET /models/1/edit
  def edit
    @brands = Brand.all
    @models = Model.prime_models
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to model_url(@model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to model_url(@model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:brand_id, :name, :parent_id, :cars_count, :description)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand_id %> 
    <%= form.collection_select :brand_id, brands, :id, :name %>
    <% model.errors.full_messages_for(:brand_id).each do |message| %>
      <div> <%= message %> </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.collection_select :parent_id, models, :id, :name, :include_blank => true %>
    <% model.errors.full_messages_for(:parent_id).each do |message| %>
      <div> <%= message %> </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :cars_count %>
    <%= form.number_field :cars_count %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing Model</h1>

<%= render 'form', model: @model, brands: @brands, models: @models %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Models</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Parent</th>
      <th>Cars count</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.brand.name%></td>
        <td><%= model.name %></td>
        <td><%= model.parent.nil? ? "" : model.parent.name %></td>
        <td><%= model.cars_count %></td>
        <td><%= model.description %></td>
        <td><%= link_to 'Show', model %></td>
        <td><%= link_to 'Edit', edit_model_path(model) %></td>
        <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form', model: @model, brands: @brands, models: @models %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @model.brand.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @model.parent_id %>
</p>

<p>
  <strong>Cars count:</strong>
  <%= @model.cars_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @model.description %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>