config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :models
  resources :dealers
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dealer.rb
# == Schema Information
#
# Table name: dealers
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Dealer < ApplicationRecord
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: %i[ show edit update destroy ]

  # GET /dealers or /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/1 or /dealers/1.json
  def show
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers or /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)

    respond_to do |format|
      if @dealer.save
        format.html { redirect_to dealer_url(@dealer), notice: "Dealer was successfully created." }
        format.json { render :show, status: :created, location: @dealer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealers/1 or /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to dealer_url(@dealer), notice: "Dealer was successfully updated." }
        format.json { render :show, status: :ok, location: @dealer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1 or /dealers/1.json
  def destroy
    @dealer.destroy

    respond_to do |format|
      format.html { redirect_to dealers_url, notice: "Dealer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dealer_params
      params.require(:dealer).permit(:name)
    end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_form.html.erb
<%= form_with(model: dealer) do |form| %>
  <% if dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
        <% dealer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dealers/edit.html.erb
<h1>Editing Dealer</h1>

<%= render 'form', dealer: @dealer %>

<%= link_to 'Show', @dealer %> |
<%= link_to 'Back', dealers_path %>

app/views/dealers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dealers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.name %></td>
        <td><%= link_to 'Show', dealer %></td>
        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealer', new_dealer_path %>

app/views/dealers/new.html.erb
<h1>New Dealer</h1>

<%= render 'form', dealer: @dealer %>

<%= link_to 'Back', dealers_path %>

app/views/dealers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dealer.name %>
</p>

<%= link_to 'Edit', edit_dealer_path(@dealer) %> |
<%= link_to 'Back', dealers_path %>