config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :models
  resources :dealers
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Brand < ApplicationRecord
  has_many :models
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[ show edit update destroy ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.description %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @brand.description %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>