config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :models
  resources :dealers
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :bigint           not null, primary key
#  name       :string
#  fueltype   :string
#  bodytype   :string
#  gearbox    :string
#  price      :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Car < ApplicationRecord
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:name, :fueltype, :bodytype, :gearbox, :price)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :fueltype %>
    <%= form.select(:fueltype, options_for_select(['Petrol', 'Diesel', 'Gaz'])) %>
  </div>

  <div class="field">
    <%= form.label :bodytype %>
    <%= form.select(:bodytype, options_for_select(['Hatchback', 'Sedan', 'Jeep', 'SUV', 'Van', 'Coupe'])) %>
  </div>

  <div class="field">
    <%= form.label :gearbox %>
    <%= form.select(:gearbox, options_for_select(['Automatic', 'Manual'])) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car, models: @models %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fueltype</th>
      <th>Bodytype</th>
      <th>Gearbox</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.fueltype %></td>
        <td><%= car.bodytype %></td>
        <td><%= car.gearbox %></td>
        <td><%= car.price %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car, models: @models %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Fueltype:</strong>
  <%= @car.fueltype %>
</p>

<p>
  <strong>Bodytype:</strong>
  <%= @car.bodytype %>
</p>

<p>
  <strong>Gearbox:</strong>
  <%= @car.gearbox %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>